version: "3"

services:

  https-benchmark-server:
    image: ghcr.io/calyptia/https-benchmark-server:master
    ports:
      - "8443:8443"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-admin-api'
      - '--web.enable-lifecycle'
      # Enable remote write, note this should be secured for any production instance
      - '--web.enable-remote-write-receiver'
    ports:
      - 9090:9090
    links:
      - cadvisor:cadvisor
      - process-exporter:process-exporter
    depends_on:
      - cadvisor
      - process-exporter
    extra_hosts:
    - "host.docker.internal:host-gateway"

  process-exporter:
    image: ncabatoff/process-exporter
    command:
      - '-procfs=/host/proc'
      - '-config.path=/process-exporter.yml'
    volumes:
      - /proc:/host/proc:ro
      - ./process-exporter.yml:/process-exporter.yml:ro
    privileged: true
    ports:
      - 9256:9256

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080

  grafana:
    image: grafana/grafana
    user: "472"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring

  loki:
    image: grafana/loki
    ports:
        - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

volumes:
  prometheus-data:
  grafana-data:
